##### Panic and Recover

- Go doesn't support exception throwing and catching, instead explicit error handling is preferred 
  to use in Go programming. In fact, Go supports an exception throw/catch alike mechanism. 
  The mechanism is called panic/recover.

```go
package main

import (
	"os"
)


func createTempFile() {
	_, err := os.Create("tmp/file")
	if err != nil {
		panic(err)
	}
}


func main() {
	createTempFile()
}
```

```bash
panic: open tmp/file: no such file or directory

goroutine 1 [running]:
main.createTempFile()
        /home/afour/.config/JetBrains/GoLand2020.2/scratches/scratch_6.go:25 +0x75
main.main()
        /home/afour/.config/JetBrains/GoLand2020.2/scratches/scratch_6.go:31 +0x25

```

```go
package main

import (
	"fmt"
	"os"
)

func createTempFile() {
	defer func() {
		r := recover()
		fmt.Println("Recovered with resp: ", r)
	}()

	_, err := os.Create("tmp/file")
	if err != nil {
		panic(err)
	}
}


func main() {
	createTempFile()
}
```

```bash
Recovered with resp:  open tmp/file: no such file or directory
```